gameListCard 컴포넌트 구현
Team-groupHi/grouphi-mvp-fe pull request #29
Opened 2024-10-20 07:02 UTC by joyswim

# 📝작업 내용
gameListCard 컴포넌트를 구현합니다.

⚠️ tailwind.config.ts 조정
- text-gray가 적용되지 않는 문제가 있어 textColors를 따로 정의했습니다.
- 카드에 쓰이는 gradient를 추가했습니다.

# 📷스크린샷(필요 시)
![image](https://github.com/user-attachments/assets/4ab16278-aeab-4ed4-86ab-e245468ad614)

# 🧪 **테스트**
```tsx
// Home
import { GameCard } from '@/components/GameListCard'

export default function Home() {
  const cards = [
    {
      title:
        '밸런스 게임 밸런스 게임밸런스 게임밸런스 게임밸런스 게임밸런스 게임',
      description:
        'description of game description of game   description of game    description of game        description of game',
      src: '/cat.jpg', // 임의의 사진을 public 폴더에 추가하세요.
    },
    {
      title: '달려라 기차',
      description:
        '기차가 나가신다 저리 비켜라 버스가 나가신다 저리 비켜라 기차가 나가신다 저리 비켜라 버스가 나가신다 저리 비켜라',
    },
    {
      title: '랜덤 질문',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam aliquid labore facilis alias minima quo excepturi optio voluptatum quidem, repellat suscipit quaerat sint ratione esse et architecto provident tempore tenetur!',
    },
  ]

  return (
    <main className="bg-gradient-purple h-screen w-screen'">
      <section className="flex justify-center gap-md p-lg h-1/4">
        {cards.map((card) => (
          <GameCard
            key={card.title}
            {...card}
          />
        ))}
      </section>
    </main>
  )
}
```

# ✨PR Point
- GameListCard를 담는 부모 요소에 flex, gap, flex-wrap 등 필요에 따라 별도로 조정해주세요.
- 제한사항
    동적인 TailwindCSS 설정을 하는 방법이 있다면 알려주세요. CSS 동적 설정이 안되어 기본 설정해두었습니다.
    1. flex 자식 요소인 GameListCard는 `basis-1/3 max-w-80 min-w-60`을 적용받습니다.
    2. description는 두 줄로 제한되어 있습니다.(`line-clamp-2`)

2024-10-20 10:54 UTC, SoJuSo requested changes
고생하셨습니다!!ㅎㅎ 다만 제 관점에서의 몇 가지 리뷰와 변경점이 있으니 확인 부탁드릴게요!
또한 현재 PR 본론에 있는 테스트 내용을 vitest PR이 업데이트 되는대로 테스트 코드로 작성해주시면 더 좋을 것 같습니다ㅎㅎ

2024-10-20 10:54 UTC, SoJuSo commented on src/components/GameListCard/GameListCard.tsx
> +interface gameCardProps {
P4; 컴포넌트 네임과 일치화 시켜주시면 더 좋을 것 같습니다~!

2024-10-20 10:54 UTC, SoJuSo commented on src/components/GameListCard/GameListCard.tsx
> +            className={`text-sm text-gray pt-2 overflow-hiddden text-ellipsis line-clamp-2 break-all`}
P2; 오타있습니다!
```suggestion
            className={`text-sm text-gray pt-2 overflow-hidden text-ellipsis line-clamp-2 break-all`}
```

2024-10-20 10:54 UTC, SoJuSo commented on src/components/GameListCard/GameListCard.tsx
> +        />
P3; layout, objectFit의 경우 13버전에서 deprecated 되었습니다!
관련 [Nextjs 한글 번역 문서](https://nextjs-ko.org/docs/app/api-reference/components/image#%EB%B2%84%EC%A0%84-%ED%9E%88%EC%8A%A4%ED%86%A0%EB%A6%AC) 
```suggestion
        <Image
          src={src}
          alt={title}
          fill
          style={{ objectFit: "cover" }}
          className="absolute"
        />
```
위와 같이 바뀌야 하는 것으로 알고 있습니다!

2024-10-20 13:09 UTC, joyswim commented on src/components/GameListCard/GameListCard.tsx
> +            className={`text-sm text-gray pt-2 overflow-hiddden text-ellipsis line-clamp-2 break-all`}
발견 감사합니다!

2024-10-20 13:09 UTC, joyswim commented on src/components/GameListCard/GameListCard.tsx
> +        />
첨부된 링크 확인해보겠습니다~

2024-10-20 13:10 UTC, joyswim commented on src/components/GameListCard/GameListCard.tsx
> +interface gameCardProps {
네 확인했습니다

2024-10-21 05:59 UTC, SoJuSo approved these changes

2024-10-23 18:18 UTC, kim-hyunjoo approved these changes
우선 리뷰가 너무 늦어져서 죄송합니다 ㅜ.ㅜ
석주님이 필요한 부분들은 다 말씀해주셔서, 지금 코드에서 더 수정할 부분은 없는 것 같습니다~
> 동적인 TailwindCSS 설정을 하는 방법이 있다면 알려주세요. CSS 동적 설정이 안되어 기본 설정해두었습니다.

저도 아직 Tailwind를 제대로 사용한 적 없어서 잘 모르겠지만 [tailwind 동적 스타일링 적용](https://velog.io/@jknine929/tailwind-%EB%8F%99%EC%A0%81-%EC%8A%A4%ED%83%80%EC%9D%BC%EB%A7%81-%EC%A0%81%EC%9A%A9) 이런 글이 있는걸 보면 가능한 것 같습니다!

> description는 두 줄로 제한되어 있습니다.(line-clamp-2) 

이 설정 덕분에 깔끔하고 일관성 있어서 좋습니다 !

2024-10-25 14:15 UTC, joyswim commented
> 우선 리뷰가 너무 늦어져서 죄송합니다 ㅜ.ㅜ 석주님이 필요한 부분들은 다 말씀해주셔서, 지금 코드에서 더 수정할 부분은 없는 것 같습니다~
> 
> > 동적인 TailwindCSS 설정을 하는 방법이 있다면 알려주세요. CSS 동적 설정이 안되어 기본 설정해두었습니다.
> 
> 저도 아직 Tailwind를 제대로 사용한 적 없어서 잘 모르겠지만 [tailwind 동적 스타일링 적용](https://velog.io/@jknine929/tailwind-%EB%8F%99%EC%A0%81-%EC%8A%A4%ED%83%80%EC%9D%BC%EB%A7%81-%EC%A0%81%EC%9A%A9) 이런 글이 있는걸 보면 가능한 것 같습니다!
> 
> > description는 두 줄로 제한되어 있습니다.(line-clamp-2)
> 
> 이 설정 덕분에 깔끔하고 일관성 있어서 좋습니다 !

동적인 TailwindCSS 설정 공유 감사합니다! 저도 같은 블로그를 참고했는데 유용하더군요ㅎㅎ

2024-10-28 08:27 UTC, merged