Button 컴포넌트 구현
Team-groupHi/grouphi-mvp-fe pull request #33
Opened 2024-10-21 10:40 UTC by joyswim

# 📝작업 내용
Button 컴포넌트를 구현합니다.

⚠️ tailwind.config.ts 수정 : Button과 관련된 부분만 일부 수정했습니다. 추후 의견 취합 후 나머지 수정 예정입니다.
```
/**
 * @param [onClick] - [필수] 버튼의 이벤트 핸들러입니다.
 * @param [variant='solid'] - 버튼의 스타일을 결정합니다.
 * @param [size='md'] - 버튼의 사이즈입니다. sm ~ xl값을 가집니다.
 * @param [shape='full'] - 버튼의 형태입니다. 사각형은 'square'를 지정해주세요.
 * @param [fontWeight='normal'] - 버튼의 fontWeight입니다.
 * @param [isDisabled=false] - 버튼의 비활성화 여부입니다.
 * @returns
 */
```

<details>
<summary>🧪 테스트 코드</summary>

```
// page.tsx
'use client';
import { Button } from '@/components';

export default function Home() {
  const handleClick = () => {
    alert('clicked!');
  };

  return (
    <div className="bg-gradient-purple flex-column flex-wrap gap-sm items-center justify-center min-h-screen">
      <section className="py-sm flex gap-sm justify-center  items-center">
        <Button onClick={handleClick}>solid</Button>
        <Button
          variant="secondary"
          onClick={handleClick}
        >
          secondary
        </Button>
        <Button
          variant="outline"
          onClick={handleClick}
        >
          outline
        </Button>
        <Button
          variant="warn"
          onClick={handleClick}
        >
          warn
        </Button>
        <Button
          variant="ghost"
          onClick={handleClick}
        >
          ghost
        </Button>
        <Button
          variant="link"
          onClick={handleClick}
        >
          link
        </Button>
      </section>
      <section className="py-sm flex gap-sm justify-center items-center">
        <Button
          onClick={handleClick}
          size="sm"
        >
          sm 버튼
        </Button>
        <Button
          onClick={handleClick}
          size="md"
        >
          md 버튼
        </Button>
        <Button
          onClick={handleClick}
          size="lg"
        >
          lg 버튼
        </Button>
        <Button
          onClick={handleClick}
          size="xl"
        >
          xl 버튼
        </Button>
      </section>
      <section className="py-sm flex gap-sm justify-center">
        <Button
          onClick={handleClick}
          isDisabled={true}
        >
          disabled
        </Button>
        <Button
          onClick={handleClick}
          shape="square"
        >
          square
        </Button>
      </section>
    </div>
  );
}

```
</details>

# 📷스크린샷
![버튼 스크린샷](https://github.com/user-attachments/assets/1f5a6a1e-d1bc-46fa-bcb0-30e76018f073)

# ✨PR Point
- Icon 버튼은 Lucide React를 알아보고 추가할 예정입니다.
- 테스트 추가 예정입니다.
- Button 컴포넌트의 커스텀을 위해 clsx 또는 classNames 라이브러리가 필요합니다. shadcn/ui 커스텀에도 사용되므로 추가하는 방안을 고려해보면 좋겠습니다.

2024-10-23 19:39 UTC, kim-hyunjoo approved these changes
수고하셨습니다!! 지정된 사이즈를 여러개 제공해주셔서 일관적인 디자인으로 사용 가능 할 것 같아요~
개발하다보니 eslint 불필요한 설정이 슬슬 보이네요.. warn 설정하는 거 좋습니다!

2024-10-23 19:39 UTC, kim-hyunjoo commented on src/components/Button/Button.tsx
> + * @param [asChild=false] - Link 컴포넌트를 중첩시킬 수 있습니다.
오호 혹시 이건 어떻게 사용해야 하는 걸까요? 
```
<Button asChild={true}>
        <Link to="/">링크</Link>
</Button>
```
이렇게 테스트 해보는데 잘 안돼서.. 이 기능의 의도가 궁금합니다!!

2024-10-23 19:39 UTC, kim-hyunjoo commented on src/components/Button/Button.tsx
> +      isDisabled = false,
button에는 기본적으로 `disabled` 속성이 있어서 이렇게 되면 `disabled`, `isDisabled` 2개가 존재하게 되는데, 굳이 같은 기능의 props가 2개 존재할 이유는 없는 것 같아서요...! 기존의 `disabled` 속성을 사용해도 되지 않을까요? 의견 한번 내봅니다🥹

일단 제가 해당 줄과 78번째 줄 삭제하고 테스트 해봤는데 잘 동작합니다!

2024-10-25 08:17 UTC, joyswim commented on src/components/Button/Button.tsx
> + * @param [asChild=false] - Link 컴포넌트를 중첩시킬 수 있습니다.
기존 shadcn/ui 기능을 최대한 활용하려고 해서 안 없앤 기능인데요.
Button의 포맷을 유지하되, 자식(예: <Link>)로 대체해서 렌더링하는 기능입니다.
개발자 페이지로 요소를 찍어보시면 <button>없이 자식 요소로 대체된 것을 알 수 있습니다!

2024-10-25 08:21 UTC, joyswim commented on src/components/Button/Button.tsx
> +      isDisabled = false,
생각해보니 그렇네요. 좋은 의견입니다! 삭제해두겠습니다.

2024-10-25 08:47 UTC, SoJuSo requested changes

2024-10-25 08:47 UTC, SoJuSo commented on .gitmessage.txt
한글로 해놨었군요...변경 감사합니다!

2024-10-25 08:47 UTC, SoJuSo commented on src/components/Button/Button.test.tsx
테스트 쪽도 컨벤션이 필요하겠네요.
일단 작성하신 내용은 좋아보입니다 👍

2024-10-25 08:47 UTC, SoJuSo commented on components.json
> +}
P2; 개행이 없어서 CRLF 에러가 나네요 한 줄 띄워주시면 좋을 것 같아요! 

이 부분에서 eslint 자동화를 하려고 조금 알아봤는데 윈도우, 맥, eslint, prettier 종합적으로 봐야해서 일단 한줄 띄는거로 해결하고 추후에 시간 날 때 자동화 찾아볼게요!

2024-10-25 14:20 UTC, joyswim commented on src/components/Button/Button.test.tsx
감사합니다! 회의 때 컨벤션 논의해봐요~ 👍

2024-10-25 14:23 UTC, joyswim commented on components.json
> +}
수정 완료됐습니다!
init 후에 따로 자동 생성된 파일이라 prettier 적용이 안 되었나 봅니다. 석주님은 PR마다 CRLF를 일일이 확인하시나요? 반복 실수가 나오는 부분이라 보완하고 싶네요!

2024-10-27 11:03 UTC, SoJuSo commented on components.json
> +}
PR마다 일일이 CRLF를 확인한다기 보다는 음...저렇게 경고가 떠 있으면 짚고 넘어가는 편입니다. 아무래도 줄바꿈에서 에러가 나는 경우가 있다고 알고 있어서요.

개인적으로 윈도우 깃에서는 이 설정을 해두었고 그 이후에는 커밋 할 때 자동으로 처리되기에 신경쓰지 않는 것 같습니다!
```
git config --global core.autocrlf true
```
[링크](https://docs.github.com/ko/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings) 첨부해드립니다!

2024-10-27 11:03 UTC, SoJuSo approved these changes

2024-10-28 05:43 UTC, joyswim commented on components.json
> +}
오 저도 설정해두어야 겠네요. 정보 감사합니다!

2024-10-28 08:08 UTC, merged