PieChart 컴포넌트
Team-groupHi/grouphi-mvp-fe pull request #52
Opened 2024-11-04 14:00 UTC by joyswim

# 📝작업 내용
Chart.js 라이브러리를 사용하여 세부 결과에 사용될 PieChart 컴포넌트를 구현합니다.
테스트 코드를 참고하여 labels, data를 전달해주세요.

# 📷스크린샷
![스크린샷](https://github.com/user-attachments/assets/bb9ee628-3d72-4191-9313-384a676b61a2)

# 🧪 테스트
```
// page.tsx
import { PieChart } from '@/components/PieChart';

const DUMMY_DATA = {
  labels: ['고양이', '강아지', '미선택'],
  data: [5, 4, 1],
};

export default function Home() {
  return (
    <div className="my-10 flex gap-10">
      <PieChart
        labels={DUMMY_DATA.labels}
        data={DUMMY_DATA.data}
      />
      <PieChart
        labels={[]}
        data={[]}
      />
      <PieChart
        labels={DUMMY_DATA.labels}
        data={DUMMY_DATA.data}
        className="bg-gray-800 w-80"
      />
    </div>
  );
}

```

# ✨PR Point
- 세부 결과 컴포넌트(detailResult)는 현재 round 정보와 user 정보가 필요하여 따로 작업하는 것이 좋을 것 같습니다. 유저를 리스트로 나열해주는 부분은 API로 유저 데이터를 어떻게 받을지 백엔드와 논의가 필요할 것 같습니다.

2024-11-05 05:32 UTC, SoJuSo requested changes
오..!! chart.js 진짜 맘에 드네요ㅎㅎ 작업 고생하셨습니다 :)

2024-11-05 05:32 UTC, SoJuSo commented on src/components/PieChart/PieChart.tsx
> +);
P2; 현재 chart.js에서 가져오는 코드 크기가 크더라구요. 혹시 이 부분에서 사용하지 않는 코드를 줄이면 문제가 생길까요? 
제가 알아본 대로 일부 미사용 코드를 제거해봤고 테스트 시 제 환경에서는 문제 없었는데 확인 한 번 부탁드립니다!
이렇게 줄일 시 여전히 크긴 하지만 129.9k 로 줄어듭니다! suggestion 남깁니다!
```suggestion
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  ChartOptions,
  ChartData,
} from 'chart.js';
import { Doughnut } from 'react-chartjs-2';
import { cn } from '@/lib/utils';

ChartJS.register(ArcElement, Tooltip, Legend);
```
![image](https://github.com/user-attachments/assets/37e9321a-a5b4-45c5-803b-b1575ae18772)

2024-11-05 05:32 UTC, SoJuSo commented on src/components/PieChart/PieChart.test.tsx
P4; 데이터가 비어있을 경우에 대해서 테스트를 추가해도 좋을 것 같습니다~!

2024-11-05 06:03 UTC, joyswim commented on src/components/PieChart/PieChart.tsx
> +);
확인해보겠습니다!

2024-11-05 06:51 UTC, joyswim commented on src/components/PieChart/PieChart.test.tsx
확인했습니다!

2024-11-13 07:44 UTC, joyswim commented on src/components/PieChart/PieChart.tsx
> +);
삭제 후 154.2k (gzipped: 53.1k)에서 129.9k (gzipped: 44.4k)로 줄었습니다!

![스크린샷](https://github.com/user-attachments/assets/b4a0a52d-5476-4c4b-a5c9-a377cbb683e0)

2024-11-13 07:53 UTC, joyswim commented on src/components/PieChart/PieChart.test.tsx
테스트 추가되었습니다.

2024-11-13 08:41 UTC, kim-hyunjoo commented on src/components/PieChart/PieChart.tsx
> +);
우와!! 혹시 이거 용량은 어떻게 볼 수 있나요?

2024-11-13 09:16 UTC, kim-hyunjoo approved these changes
확인했습니다! 테스트 코드까지 깔끔한 것 같아요.
P5; 디자인에 의견 내자면 라벨과 차트 차이의 간격이 조금만 더 생기면 좋을 것 같아요!

2024-11-13 09:16 UTC, kim-hyunjoo commented on src/components/PieChart/PieChart.tsx
> +        bottom: 10,
이 패딩값은 어디에 적용되는건가요?

2024-11-16 00:08 UTC, SoJuSo commented on src/components/PieChart/PieChart.tsx
> +);
@kim-hyunjoo Import Cost라는 vsc 라이브러리입니다!
https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost

2024-11-16 00:09 UTC, SoJuSo approved these changes
확인했습니다~ 👍

2024-11-18 05:14 UTC, joyswim commented on src/components/PieChart/PieChart.tsx
> +        bottom: 10,
그래프의 아래 부분입니다! hover시 그래프가 커지는 부분이 잘려서 아랫부분에 padding을 적용했습니다.

2024-11-18 05:34 UTC, merged